#!/usr/bin/env bash
#Install nginx on your web-01 server with automation
#Nginx should be listening on port 80
#using curl, it must return a page that contains the string Hello World!
apt-get update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx restart
