#!/usr/bin/env bash
# also displays 10 Best School but 9th iter is "Best Schhol and Hi in the next line"

i=1

while [ "$i" -le 10 ]
do
    echo "Best School"
    if [ $i -eq 9 ]
    then
        echo "Hi"
    fi
    ((i++))
done
