#!/usr/bin/env bash
# same with the rest but prints but "bad luck for the 4th iteration"
# "good luck" for 8th and "Best School" for the rest

i=1

while [ "$i" -le 10 ]
do
    if [ "$i" -eq 4 ]
    then
        echo "bad luck"
    elif [ "$i" -eq 8 ]
    then
        echo "good luck"
    else echo "Best School"
    fi
    ((i++))
done
