#!/usr/bin/env bash
# print nums from 1-20, but after 4 "bad luck from China", 9 "bad luck from Japan"
# and 17 "bad luck from Italy"

i=1

while [ "$i" -le 20 ]
do
  echo "$i"
  case $i in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( i++ ))
done
